#pragma once
#ifndef RLAQHADMLGPEJWNDQHRQKDWLAOZMFH_RESOURCES_H
#define RLAQHADMLGPEJWNDQHRQKDWLAOZMFH_RESOURCES_H

#define IDI_MAIN_ICON           101
#define IDR_FONT_NOTOSANS       201
#define IDR_FONT_POPPINS        202
#define IDR_FONT_ROBOTO         203
#define IDR_FONT_D2CODING       204

#endif //RLAQHADMLGPEJWNDQHRQKDWLAOZMFH_RESOURCES_H
