#pragma once
#ifndef RLAQHADMLGPEJWNDQHRQKDWLAOZMFH_RESOURCES_H
#define RLAQHADMLGPEJWNDQHRQKDWLAOZMFH_RESOURCES_H

#define IDI_MAIN_ICON               101
#define IDR_LOGO_PNG                102
#define IDR_LOGO_SYMBOL             103

#define IDR_FONT_POPPINS            200
#define IDR_FONT_ROBOTO             201
#define IDR_FONT_D2CODING           202

#define IDR_FONT_NOTOSANS           301
#endif //RLAQHADMLGPEJWNDQHRQKDWLAOZMFH_RESOURCES_H
